from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any

from rest_framework import serializers

Sanitizer = Callable[[str], str]
ValidatorCallable = Callable[[str], None]


class OllowEditorHTMLField(serializers.CharField):
    """Serializer field for HTML generated by the OllowEditor frontend."""

    def __init__(
        self,
        *args: Any,
        sanitizer: Sanitizer | None = None,
        validator: ValidatorCallable | None = None,
        style: Mapping[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        kwargs.setdefault("trim_whitespace", False)

        validators = list(kwargs.pop("validators", []))
        if validator is not None:
            validators.append(validator)
        if validators:
            kwargs["validators"] = validators

        style_config = {"base_template": "textarea.html"}
        if style is not None:
            style_config.update(dict(style))
        kwargs["style"] = style_config

        super().__init__(*args, **kwargs)
        self.sanitizer = sanitizer

    def to_internal_value(self, data: Any) -> str | None:
        value = super().to_internal_value(data)
        if value is None or self.sanitizer is None:
            return value

        try:
            sanitized = self.sanitizer(value)
        except serializers.ValidationError:
            raise
        except Exception as exc:
            raise serializers.ValidationError(f"HTML sanitizer failed: {exc}") from exc

        if not isinstance(sanitized, str):
            raise serializers.ValidationError("HTML sanitizer must return a string.")

        return sanitized
